# Build environment
FROM node:10.13.0-alpine AS builder
RUN mkdir /app
WORKDIR /app
COPY ./app/package*.json /app/
RUN npm install
RUN npm install react-scripts@2.0.3 -g
COPY ./app /app
RUN npm run build

# Production environment
FROM nginx:latest
EXPOSE 80
COPY --from=builder /app/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
